#!/bin/bash

mongo < reset_simulation.mongo
node journeys.js $2
curl -v -H "Accept: application/json" -H "Content-type: application/json" -X POST http://localhost:3000/simulations/$1/journeys -d @new_journeys.json
echo
rm new_journeys.json
