#!/bin/bash
#!/bin/bash

#Move to the right directory
cd $(dirname $0)

#Script proper
mongo < reset_all_simulations.mongo

if [ $3 ]; then
  ./batch_journeys $1 $3
fi

python3 non_colliding.py $1 $2 $4
