#!/bin/bash

cd $(dirname $0)

SIM_ID=$1
INPUT_FILE=logs/stress_test_$SIM_ID.log
OUTPUT_DIR=plots/chart$2
DATA_FILE=$OUTPUT_DIR/data.json

mkdir -p $OUTPUT_DIR

cp plots/chart.js $OUTPUT_DIR/chart.js
cp plots/chart.html $OUTPUT_DIR/chart.html

echo "[" > $DATA_FILE
tail -n +2 $INPUT_FILE >> $DATA_FILE
echo "]" >> $DATA_FILE

open $OUTPUT_DIR/chart.html
