#!/bin/bash

cd $(dirname $0)
mkdir -p logs

test $4 && SIM_ID=$4 || SIM_ID=$(curl http://localhost:3000/create-simulation -X POST)
rm logs/stress_test_$SIM_ID.log
for NUM_CARS in $(jot 4 $1 $2)
  do
    eval ../sample_algorithms/exec_sim $SIM_ID Experiment $NUM_CARS $3
  done
echo Experiment simulation ID:
echo $SIM_ID
